export const faqs = [
  {
    q_en: 'Where is TaiwanWay located?',
    a_en: 'TaiwanWay (臺灣味) is located at 26 South St, Middletown, NY 10940. We are in Orange County, about 60 miles northwest of New York City, serving the Hudson Valley region.',
    q_zh: '臺灣味在哪裡？',
    a_zh: '臺灣味位於紐約州 Middletown 的 26 South St（郵遞區號 10940），在 Orange County，距離紐約市約 60 英里，服務 Hudson Valley 地區。',
    q_es: '¿Dónde está ubicado TaiwanWay?',
    a_es: 'TaiwanWay está ubicado en 26 South St, Middletown, NY 10940, en el condado de Orange, a unas 60 millas al noroeste de la ciudad de Nueva York.',
  },
  {
    q_en: 'What are TaiwanWay\u2019s hours?',
    a_en: 'We are open Monday, Tuesday, Friday, and Saturday from 11:00 AM to 7:00 PM. We are closed on Wednesdays, Thursdays, and Sundays.',
    q_zh: '營業時間是？',
    a_zh: '週一、週二、週五、週六 11:00 AM – 7:00 PM。週三、週四、週日公休。',
    q_es: '¿Cuál es el horario?',
    a_es: 'Abrimos lunes, martes, viernes y sábado de 11:00 AM a 7:00 PM. Cerrado miércoles, jueves y domingo.',
  },
  {
    q_en: 'Do you offer delivery?',
    a_en: 'Yes. TaiwanWay offers delivery through Uber Eats throughout Middletown and nearby Orange County areas. You can also order online for in-store pickup at order.taiwanwayny.com.',
    q_zh: '有外送嗎？',
    a_zh: '有。我們透過 Uber Eats 提供外送服務，涵蓋 Middletown 及 Orange County 周邊地區。也可以在 order.taiwanwayny.com 線上訂餐到店自取。',
    q_es: '¿Ofrecen entrega a domicilio?',
    a_es: 'Sí. TaiwanWay ofrece entrega a través de Uber Eats en Middletown y áreas cercanas del condado de Orange. También pueden ordenar en línea para recoger en la tienda en order.taiwanwayny.com.',
  },
  {
    q_en: 'What is TaiwanWay\u2019s signature dish?',
    a_en: 'Our most popular dishes are Beef Noodle Soup (牛肉麵) — a Taiwanese classic with hand-pulled noodles and slow-braised beef in rich broth — and Braised Pork Rice (滷肉飯), savory minced pork over fragrant white rice. Both are prepared using traditional Taiwanese family recipes.',
    q_zh: '招牌菜是什麼？',
    a_zh: '牛肉麵和滷肉飯是最受歡迎的招牌。牛肉麵使用手工麵條和慢燉牛肉，湯頭濃郁；滷肉飯則是傳統台灣家常菜。兩道都依照家傳食譜製作。',
    q_es: '¿Cuál es el plato estrella?',
    a_es: 'Los más populares son la Sopa de Fideos con Ternera (牛肉麵) y el Arroz con Cerdo Estofado (滷肉飯), ambos preparados con recetas tradicionales taiwanesas.',
  },
  {
    q_en: 'Is your bubble tea authentic Taiwanese?',
    a_en: 'Yes. Our tea leaves are air-freighted directly from Taiwan \u2014 honey-scented black tea, jasmine green tea, high-mountain oolong, plus Kyoto Ippodo matcha. Pure, unblended, original Taiwanese flavor. Tapioca pearls are cooked fresh every morning; sugar and ice levels are fully customizable.',
    q_zh: '珍珠奶茶是正宗台灣口味嗎？',
    a_zh: '是的。我們的茶葉從台灣直接空運到紐約——蜜香紅茶、茉莉綠茶、高山烏龍，以及京都一保堂的抹茶，原汁原味、未經調味。珍珠每日現煮，糖度冰塊皆可客製。',
    q_es: '¿Su bubble tea es auténtico taiwanés?',
    a_es: 'Sí. Nuestras hojas de té vienen directamente por aire desde Taiwán — té negro miel, té verde de jazmín, oolong de alta montaña y matcha Ippodo de Kioto. Sabor original, puro, sin alteración. Perlas de tapioca cocinadas frescas cada mañana; nivel de azúcar y hielo personalizable.',
  },
  {
    q_en: 'Do you have vegetarian or vegan options?',
    a_en: 'Yes. Vegetarian-friendly options include all our teas (jasmine green, oolong, matcha, brown sugar bubble tea), homemade pineapple cake, and side dishes like Taiwanese kimchi and chilled peanuts with celery. Please ask staff for the latest vegetarian menu.',
    q_zh: '有素食選項嗎？',
    a_zh: '有。所有飲品（茉莉綠茶、烏龍茶、抹茶、黑糖珍奶）、自製鳳梨酥、台式泡菜、涼拌花生小菜皆為素食。詳細素食菜單請詢問店員。',
    q_es: '¿Tienen opciones vegetarianas o veganas?',
    a_es: 'Sí. Todas nuestras bebidas, el pastel de piña casero y varios acompañamientos como el kimchi taiwanés son vegetarianos. Pregunte al personal por el menú actualizado.',
  },
  {
    q_en: 'Do you accept reservations?',
    a_en: 'Yes, we accept reservations by phone or in person. Book ahead for peak hours (weekend lunch, Friday evenings). We also have a private room upstairs for larger groups. Call 845-381-1002.',
    q_zh: '可以訂位嗎？',
    a_zh: '可以。接受電話或現場訂位，用餐尖峰時段建議提前預約。二樓另有獨立包廂，適合團體聚會。訂位請致電 845-381-1002。',
    q_es: '¿Aceptan reservaciones?',
    a_es: 'Sí, aceptamos reservaciones por teléfono o en persona. Reserve con antelación en horas pico. También disponemos de sala privada en el segundo piso para grupos. Llame al 845-381-1002.',
  },
  {
    q_en: 'Is there parking available?',
    a_en: 'Yes. Street parking is available along South St and surrounding streets in downtown Middletown. Free municipal parking lots are also within a short walk.',
    q_zh: '附近有停車位嗎？',
    a_zh: '有。South St 及周邊街道有路邊停車位，附近也有免費的市立停車場，步行可達。',
    q_es: '¿Hay estacionamiento?',
    a_es: 'Sí. Hay estacionamiento en la calle a lo largo de South St y estacionamientos municipales gratuitos a poca distancia.',
  },
  {
    q_en: 'Where does your tea come from?',
    a_en: 'Our loose-leaf teas are sourced directly from Taiwan, including high-mountain Oolong (Jin Xuan, Alishan), Dong Pian winter tea, Tie Guan Yin, and single-origin Alishan Black Tea. Matcha comes from Ippodo in Kyoto, Japan.',
    q_zh: '茶葉來源？',
    a_zh: '散茶皆從台灣直接進口，包含高山烏龍（金萱、阿里山）、冬片、鐵觀音、阿里山紅茶等。抹茶來自日本京都一保堂。',
    q_es: '¿De dónde viene su té?',
    a_es: 'Nuestros tés sueltos vienen directamente de Taiwán (oolong de alta montaña, Tie Guan Yin, té negro de Alishan). El matcha es de Ippodo en Kioto, Japón.',
  },
  {
    q_en: 'Do you sell Taiwanese pineapple cake?',
    a_en: 'Yes. We make Taiwanese Pineapple Cake (鳳梨酥) fresh daily using traditional buttery pastry and winter melon–pineapple filling. Available individually or as gift boxes — perfect for souvenirs or corporate gifts.',
    q_zh: '有賣台灣鳳梨酥嗎？',
    a_zh: '有。鳳梨酥每日手工現做，採用傳統奶油酥皮與冬瓜鳳梨內餡。單顆或禮盒皆有販售，適合送禮或公司伴手禮。',
    q_es: '¿Venden pastel de piña taiwanés?',
    a_es: 'Sí. Hacemos pastel de piña taiwanés (鳳梨酥) diariamente con masa tradicional y relleno de piña con melón de invierno. Disponible individualmente o en cajas de regalo.',
  },
  {
    q_en: 'What languages do you serve?',
    a_en: 'Our staff can serve customers in English, Traditional Chinese (中文), and Spanish (Español). Our website, menu, and ordering system are fully trilingual.',
    q_zh: '店員會說什麼語言？',
    a_zh: '店員可以用英文、中文、西班牙文為您服務。網站、菜單、線上點餐系統都是三語介面。',
    q_es: '¿Qué idiomas hablan?',
    a_es: 'Nuestro personal atiende en inglés, chino tradicional y español. Nuestro sitio web y menú son completamente trilingües.',
  },
] as const
